clc;
clear('all');
warning('off','all');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SIMULATION CONFIGURATION %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
PARAMETERS = {};
PARAMETERS.SIMULATION = {};
PARAMETERS.CONTROL = {};
PARAMETERS.DISTURBANCE = {};
PARAMETERS.PLOT = {};
PARAMETERS.PLANT = {};
PARAMETERS.REFERENCE = {};

PARAMETERS.SIMULATION.SETTLING_TIME = 1.0;
PARAMETERS.PLANT.X_1_MAX = pi;
PARAMETERS.PLANT.X_2_MAX = 2.0*pi;
PARAMETERS.CONTROL.GAIN = 2.0; 
PARAMETERS.CONTROL.MU = 7; 
PARAMETERS.CONTROL.Z_MIN_1 = 0.02; 
PARAMETERS.SIMULATION.TOTAL_TIME = 3;
PARAMETERS.PLOT.CREATE_PDF = 0;
PARAMETERS.PLOT.FONT_SIZE = 14;
PARAMETERS.DISTURBANCE.D_0 = 0;
PARAMETERS.DISTURBANCE.D_0_EST = 5;
PARAMETERS.DISTURBANCE.FREQUENCY = 10;
PARAMETERS.PLANT.GRAVITY = 9.8;
PARAMETERS.PLANT.CART_MASS = 1;
PARAMETERS.PLANT.POLE_MASS = 0.1;
PARAMETERS.PLANT.POLE_HALF_LENGTH = 0.5;
PARAMETERS.PLANT.INITIAL_STATE = [0.0 0.0]';
PARAMETERS.PLANT.INITIAL_STATE = [0.9 0.5*pi]'; 
% PARAMETERS.PLANT.INITIAL_STATE = [1.2 0.1]'; 
% PARAMETERS.PLANT.INITIAL_STATE = [0.5*pi/2.0 2*pi]';
