function [disturbance, PARAMETERS]  = function_calculate_disturbance(time, state, PARAMETERS)
    if PARAMETERS.DISTURBANCE.TYPE == 1
        disturbance = 1*(sin(PARAMETERS.DISTURBANCE.FREQUENCY*state(1,1)) + cos(state(2,1)));
        PARAMETERS.DISTURBANCE.DOT_FREQUENCY_MAX = max(PARAMETERS.DISTURBANCE.FREQUENCY, 1);
    elseif PARAMETERS.DISTURBANCE.TYPE == 2
        disturbance = 2.85*cos(8.7*time + 0.36)*exp(sin(4.1*time + 0.13)) + 0.95*sin(2.1*time - 0.76);
        PARAMETERS.DISTURBANCE.DOT_FREQUENCY_MAX = 2.85*8.7 + 0.95*2.1;
    elseif PARAMETERS.DISTURBANCE.TYPE == 3
        disturbance = 0.75*PARAMETERS.DISTURBANCE.D_0 + 0.25*PARAMETERS.DISTURBANCE.D_0*cos(0.2*PARAMETERS.DISTURBANCE.FREQUENCY*time) + 0.25*PARAMETERS.DISTURBANCE.D_0*sin(PARAMETERS.DISTURBANCE.FREQUENCY*time + 0.36)*exp(sin(1.21*PARAMETERS.DISTURBANCE.FREQUENCY*time + 0.13));  
        PARAMETERS.DISTURBANCE.DOT_FREQUENCY_MAX = max(PARAMETERS.DISTURBANCE.D_0*0.5*PARAMETERS.DISTURBANCE.FREQUENCY, 1); %max(0.25*0.2*PARAMETERS.DISTURBANCE.FREQUENCY, 0.25*PARAMETERS.DISTURBANCE.D_0*PARAMETERS.DISTURBANCE.FREQUENCY);
    end
end