% Configure
configuration;

PARAMETERS.DISTURBANCE.D_0 = 0;
PARAMETERS.DISTURBANCE.D_0_EST = PARAMETERS.DISTURBANCE.D_0 + 1;
PARAMETERS.PLOT.CREATE_PDF = 1;
PARAMETERS.SIMULATION.SCENARIO = 1;
if PARAMETERS.SIMULATION.SCENARIO == 1
    PARAMETERS.SIMULATION.SAMPLING_TIME = 1e-3;
    PARAMETERS.DISTURBANCE.TYPE = 1;
elseif PARAMETERS.SIMULATION.SCENARIO == 2
    PARAMETERS.SIMULATION.SAMPLING_TIME = 1e-3;
    PARAMETERS.DISTURBANCE.TYPE = 2;
elseif PARAMETERS.SIMULATION.SCENARIO == 3
    PARAMETERS.SIMULATION.SAMPLING_TIME = 1e-3;
    PARAMETERS.DISTURBANCE.TYPE = 3;
end
PARAMETERS.SIMULATION.TIME = 0:PARAMETERS.SIMULATION.SAMPLING_TIME:PARAMETERS.SIMULATION.TOTAL_TIME;
PARAMETERS.SIMULATION.TOTAL_STEPS = size(PARAMETERS.SIMULATION.TIME, 2);

% Run simulation
SIMULATION_DATA = run_simulation(PARAMETERS);

% Plot simulation
plot_simulation(SIMULATION_DATA, PARAMETERS);